### ISSUE TITLE
Update kubernetes examples to assume kubernetes 1.4

### ISSUE THREAD

**Issue by klingerf** [BuoyantIO/linkerd-examples#80]
For the kubernetes examples in this repo and the getting started guides on [linkerd.io](https://linkerd.io), I'd like to start assuming that folks are running kubernetes 1.4+, which gives us access to the node name as part of the downward api. This will make our example configs and guides a lot more intelligible.

For instance, in our [current getting started guide](https://linkerd.io/getting-started/k8s-daemonset/), we link to [this hostIP.sh script](https://raw.githubusercontent.com/BuoyantIO/linkerd-examples/master/k8s-daemonset/helloworld/hostIP.sh), and have the following config:

```
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NS
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command:
        - "/bin/bash"
        - "-c"
        - "http_proxy=`./hostIP.sh`:4140 myCoolApp"
```

Instead, if we assume kubernetes 1.4+, then we can omit the script, we can stop overriding the container's default entrypoint via the `command:` field, and we can constrain all of the changes needed setup the `http_proxy` environment variable to the `env:` field, with the following config:

```
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: http_proxy
          value: $(NODE_NAME):4140
```

We could still provide the hostIP.sh script as a legacy option, but it shouldn't be the initially recommended approach.

As part of this change, I think we should rename [hello-world.yml](https://github.com/BuoyantIO/linkerd-examples/blob/master/k8s-daemonset/k8s/hello-world.yml) to `hello-world-legacy.yml`, and [hello-world-1_4.yml](https://github.com/BuoyantIO/linkerd-examples/blob/master/k8s-daemonset/k8s/hello-world-1_4.yml) to `hello-world.yml`.
